language: scala
scala:
   - 2.10.4
before_install:
  - sudo pip install --upgrade conda
install:
# Download spark 1.4.1
  - "wget http://download.nextag.com/apache/spark/spark-1.4.1/spark-1.4.1-bin-hadoop2.4.tgz"
  - "tar -xvf spark-1.3.1-bin-hadoop2.4.tgz"
  # install python deps
  - sudo conda init
  - deps='pip requests nose sphinx pep8'
  - conda create -p $HOME/py --yes $deps "python=2.7"
  - export PATH=$HOME/py/bin:$PATH
  - pip install unittest2
script:
  - ./sbt/sbt scalastyle
  - ./sbt/sbt test
  - "export SPARK_HOME=./spark-1.4.1-bin-hadoop2.4/"
  - cd python; ./run-tests; cd ..
  - "pep8 --ignore=E402 ./python"